<a href="https://colab.research.google.com/github/foryoudrizzle14/-kimchi-recipe/blob/main/AI%20%EA%B3%A0%EA%B0%9D%20%EC%9D%B4%ED%83%88%20%EC%98%88%EC%B8%A1%20%EB%AA%A8%EB%8D%B8%20%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [ ]:
data = [[1,2],[3,4]]


tensor = torch.tensor(data, dtype = torch.float)

In [ ]:
print(tensor.dtype,'\n', tensor)

torch.float32 
 tensor([[1., 2.],
        [3., 4.]])


In [ ]:
np_array = np.array(data)
tensor1 = torch.from_numpy(np_array)

print(tensor1)

tensor([[1, 2],
        [3, 4]])


In [ ]:
ones = torch.ones_like(tensor)

rands = torch.rand_like(tensor)

print(ones, "\n",rands)

tensor([[1., 1.],
        [1., 1.]]) 
 tensor([[0.1492, 0.2094],
        [0.6569, 0.1102]])


In [ ]:
tensor.dtype
tensor.shape
tensor.size()

tensor.device

device(type='cpu')

In [ ]:
import torch

if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print(f"Device tensor is stored on: {tensor.device}")


Device tensor is stored on: cuda:0


In [ ]:
data = [[1,2,3],[4,5,6],[7,8,9,]]

tensor2 = torch.tensor(data, dtype = torch.float)

print(tensor2)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
tensor2[0,1]

tensor(2.)

In [ ]:
tensor2[:2,]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.cat([tensor2,tensor2])

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
tensor_new = torch.cat([tensor2,tensor2])

print(tensor_new.shape)
print(tensor_new)

torch.Size([6, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [ ]:
tensor_new2 = torch.cat([tensor2,tensor2],dim = 1)

print(tensor_new2.shape)
print(tensor_new2)

torch.Size([3, 6])
tensor([[1., 2., 3., 1., 2., 3.],
        [4., 5., 6., 4., 5., 6.],
        [7., 8., 9., 7., 8., 9.]])


텐서 연산


In [ ]:
tensor + tensor

tensor([[2., 4.],
        [6., 8.]])

In [ ]:
3 * tensor

tensor([[ 3.,  6.],
        [ 9., 12.]])

행렬곱

In [ ]:
tensor.mul(tensor)

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [ ]:
tensor.matmul(tensor)

tensor([[ 7., 10.],
        [15., 22.]])

In [ ]:
tensor@tensor

tensor([[ 7., 10.],
        [15., 22.]])

최대값 argmax

In [ ]:
tensor2

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [ ]:
tensor2.max()

tensor(9.)

In [ ]:
tensor2.max(dim=0)

torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))

In [ ]:
tensor2.argmax()

tensor(8)

In [ ]:
tensor2.argmax(dim=0)

tensor([2, 2, 2])

In [ ]:
tensor4 =torch.tensor([[1., 2., 3.,10.],[4., 5., 6.,11.],[7., 8., 9., 12.]])

print(tensor4)
print(tensor4.shape)

tensor([[ 1.,  2.,  3., 10.],
        [ 4.,  5.,  6., 11.],
        [ 7.,  8.,  9., 12.]])
torch.Size([3, 4])


In [ ]:
tensor4.max(dim=0)

torch.return_types.max(
values=tensor([ 7.,  8.,  9., 12.]),
indices=tensor([2, 2, 2, 2]))


reshape

In [ ]:
tensor4

tensor([[ 1.,  2.,  3., 10.],
        [ 4.,  5.,  6., 11.],
        [ 7.,  8.,  9., 12.]])

In [ ]:
tensor4.reshape(2,6)

tensor([[ 1.,  2.,  3., 10.,  4.,  5.],
        [ 6., 11.,  7.,  8.,  9., 12.]])

In [ ]:
tensor4.reshape(2,-1)

tensor([[ 1.,  2.,  3., 10.,  4.,  5.],
        [ 6., 11.,  7.,  8.,  9., 12.]])

In [ ]:
tensor4.reshape(4,-1)

tensor([[ 1.,  2.,  3.],
        [10.,  4.,  5.],
        [ 6., 11.,  7.],
        [ 8.,  9., 12.]])

In [ ]:
tensor4.view(2,6)

tensor([[ 1.,  2.,  3., 10.,  4.,  5.],
        [ 6., 11.,  7.,  8.,  9., 12.]])

In [ ]:
tensor4.shape

torch.Size([3, 4])

In [ ]:
tensor_new4 =torch.unsqueeze(tensor4, dim=0)

print(tensor_new4, '\n',tensor_new4.shape)

tensor([[[ 1.,  2.,  3., 10.],
         [ 4.,  5.,  6., 11.],
         [ 7.,  8.,  9., 12.]]]) 
 torch.Size([1, 3, 4])


In [ ]:
tensor_new4 =torch.unsqueeze(tensor4, dim=1)

print(tensor_new4, '\n',tensor_new4.shape)

tensor([[[ 1.,  2.,  3., 10.]],

        [[ 4.,  5.,  6., 11.]],

        [[ 7.,  8.,  9., 12.]]]) 
 torch.Size([3, 1, 4])


In [ ]:
tensor_new4 =torch.unsqueeze(tensor4, dim=2)

print(tensor_new4, '\n',tensor_new4.shape)

tensor([[[ 1.],
         [ 2.],
         [ 3.],
         [10.]],

        [[ 4.],
         [ 5.],
         [ 6.],
         [11.]],

        [[ 7.],
         [ 8.],
         [ 9.],
         [12.]]]) 
 torch.Size([3, 4, 1])


In [ ]:
tensor_new4 =torch.unsqueeze(tensor4, dim=0)

print(tensor_new4, '\n',tensor_new4.shape)

tensor([[[ 1.,  2.,  3., 10.],
         [ 4.,  5.,  6., 11.],
         [ 7.,  8.,  9., 12.]]]) 
 torch.Size([1, 3, 4])


In [ ]:
import torch

# Example tensor with a singleton dimension at index 0
tensor_new4 = torch.randn(1, 3, 2)  # Shape [1, 3, 2]

# Squeeze the tensor at dimension 0
torch_new4_1 = torch.squeeze(tensor_new4, dim=0)

# Print the shape and the tensor
print(tensor_new4.shape, '\n', tensor_new4)


torch.Size([1, 3, 2]) 
 tensor([[[-1.3931, -0.0527],
         [ 0.6126, -2.6474],
         [ 1.6074,  0.4436]]])


In [ ]:
m1 = torch.FloatTensor([3,3])
m2 = torch.FloatTensor([2,2])

print(m1 + m2)

tensor([5., 5.])


In [ ]:
m1 = torch.FloatTensor([1,2])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([4., 5.])


In [ ]:
m1 = torch.FloatTensor([[1,2],[3,4]])
m2 = torch.FloatTensor([3,4])
print(m1 + m2)

tensor([[4., 6.],
        [6., 8.]])
